[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://tzjiovkpwkpqckfswfmf.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6amlvdmtwd2twcWNrZnN3Zm1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxODgxMjIsImV4cCI6MjA2Mjc2NDEyMn0.l6ktBaHuP8CEV3mwSaRLh2JU9Xw_Xl3RK93qEG8dKGQ"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuración para permitir cargas de archivos grandes
[functions]
  node_bundler = "esbuild"
  included_files = ["!node_modules/@esbuild/darwin-arm64/bin/esbuild"]

# Cabeceras CORS para Supabase
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    
# Permitir tamaños de carga grandes para las imágenes
[build.processing]
  skip_processing = true

[build.processing.images]
  compress = false